[ecommerce] Using Shared Partials
Platform-OS/platformos-documentation pull request #275
Opened 2018-12-13 15:45 UTC by chrisdanek

2018-12-13 22:40 UTC, pavelloz commented on marketplace_builder/views/pages/use-cases/e-commerce/using-shared-partials.liquid
> +#### marketplace_builder/views/partials/forms/error.html
```suggestion
#### marketplace_builder/views/partials/forms/error.liquid
```

2018-12-13 22:40 UTC, pavelloz commented on marketplace_builder/views/pages/use-cases/e-commerce/using-shared-partials.liquid
> +#### marketplace_builder/views/partials/forms/label.html
```suggestion
#### marketplace_builder/views/partials/forms/label.liquid
```

2018-12-13 22:42 UTC, pavelloz commented
This looks like a good candidate to be a tutorial on its own, referenced from other places - one of them e-commerce

2018-12-14 08:20 UTC, diana-lakatos commented
@pavelloz I think that the topic (how to use partials) should be explained in a beginner tutorial, but for that a simpler example would work better.

2018-12-14 13:28 UTC, diana-lakatos requested changes

2018-12-14 13:28 UTC, diana-lakatos commented on marketplace_builder/views/pages/use-cases/e-commerce/using-shared-partials.liquid
> +2. Assign values part: most of the optional parameters should have some kind
@chrisdanek This sentence is difficult to understand/unfinished. Could you please clarify?

2018-12-14 13:28 UTC, diana-lakatos commented on marketplace_builder/views/pages/use-cases/e-commerce/using-shared-partials.liquid
> +With these simple changes you are now ready to start building the admin panel in earnest. In the next part you’ll define all constants and enums for your application, so that it’s easier than relying
@chrisdanek Could you add some more explicit explanation for using constants and enums? Or we could just remove the explanation here, and explain it in the next tutorial.

2018-12-14 13:39 UTC, chrisdanek commented on marketplace_builder/views/pages/use-cases/e-commerce/using-shared-partials.liquid
> +With these simple changes you are now ready to start building the admin panel in earnest. In the next part you’ll define all constants and enums for your application, so that it’s easier than relying
Next tutorial is all about this topic. I don’t know how to explain it in just one sentence

2018-12-14 13:45 UTC, chrisdanek commented on marketplace_builder/views/pages/use-cases/e-commerce/using-shared-partials.liquid
> +2. Assign values part: most of the optional parameters should have some kind
I get distracted easily... Finished the sentence now

2018-12-14 18:11 UTC, lemingos approved these changes

2018-12-17 10:27 UTC, diana-lakatos commented on marketplace_builder/views/pages/use-cases/e-commerce/using-shared-partials.liquid
> +With these simple changes you are now ready to start building the admin panel in earnest. In the next part you’ll define all constants and enums for your application, so that it’s easier than relying
I understand. Then I think we should remove the explanation here and leave it to the next topic.

2018-12-17 10:29 UTC, diana-lakatos approved these changes

2018-12-17 10:29 UTC, merged