add information about server side rendering
Platform-OS/platformos-documentation pull request #319
Opened 2019-01-17 16:02 UTC by Slashek

2019-01-17 16:13 UTC, pavelloz commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +## Decorating user input with `default_payload` json
```suggestion
## Modifying user input with `default_payload` json
```

2019-01-17 16:14 UTC, pavelloz requested changes
please use relative urls in your links (so that they work on staging as well)

2019-01-17 16:16 UTC, pavelloz commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +The next step is to process the callback synchronously.
It looks like this article could use an ordered list or at least numbers before each step

2019-01-17 16:17 UTC, pavelloz commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +The next step is to schedule pocessing async callbacks in the background.
```suggestion
The next step is to schedule processing async callbacks in the background.
```

2019-01-17 16:18 UTC, pavelloz commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +The next step is to schedule all notifications: email, sms, api calls, to be processed in the background
```suggestion
The next step is to schedule all notifications (email, sms, api calls) to be processed in the background.
```

2019-01-18 12:06 UTC, Slashek commented
@pavelloz updated, and added one note and one tip

2019-01-18 16:15 UTC, pavelloz approved these changes

2019-01-18 16:16 UTC, pavelloz commented
@diana-lakatos - merge if you decide its ready :)

2019-01-19 19:18 UTC, lemingos requested changes

2019-01-19 19:18 UTC, lemingos commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +  title: Form Server Side Processing
Server-Side

2019-01-19 19:18 UTC, lemingos commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +The result of merging user's input with default_payload is then run against validation rules defined for each field. If at least one validation fails, the server renders response based on the format.
```suggestion
The result of merging user's input with default_payload is then run against validation rules defined for each field. If at least one validation fails, the server renders response based on the format. For HTML the errors are added to `form_builder` variable inside the relevant field and server renders [Page](/tutorials/pages/pages) based on `page_id` parameter passed to the server. Additionally, the flash_alert is evaluated and set if provided in the configuration. It's then accessible using `context` variable. For JSON, a json object is returned with populated `errors` key. The status code is 200 in both scenarios.
```

2019-01-19 19:18 UTC, lemingos commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +It is possible to send request via AJAX, but receive HTML response from the server. The trick is to explicitly set the format to html by appending to the rest endpoint `.html`, for example `/api/user
URL

2019-01-19 19:18 UTC, lemingos commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +This topic explains form server side processing in PlatformOS when user submits form.
platformOS

2019-01-19 19:18 UTC, lemingos commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +## 2. Find FormConfiguration based on `form_configuration_name` or `form_configuration_name` parameter
form_configuration_id ?

2019-01-19 19:18 UTC, lemingos commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +## 4. ResourceOwner authorization
I think better Resource Owner

2019-01-19 19:18 UTC, lemingos commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +The next step is to extend/overwrite user's input with `default_payload`. This is the place when liquid is evaluated server side. The most useful variables here used to build default_payload are `con
JSON

2019-01-19 19:18 UTC, lemingos commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +It is possible to send request via AJAX, but receive HTML response from the server. The trick is to explicitly set the format to html by appending to the rest endpoint `.html`, for example `/api/user
and HTML

2019-01-19 19:18 UTC, lemingos commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +It is possible to send request via AJAX, but receive HTML response from the server. The trick is to explicitly set the format to html by appending to the rest endpoint `.html`, for example `/api/user
and JSON :)

2019-01-19 20:29 UTC, ghost commented on marketplace_builder/views/pages/tutorials/forms/form-server-side-processing.liquid
> +The new state of the resource is persisted in the database. In case of rare scenario of internal server error, the changes are rollbacked and server renders 500 error.
rollbacked -> rolled back

2019-01-20 11:11 UTC, Slashek commented
updated globally "PlatformOS" -> "platformOS"

2019-01-20 18:11 UTC, lemingos approved these changes

2019-01-20 19:39 UTC, pavelloz requested changes
From what i remember Diana wanted to keep capitalized `P` if its in the beginning of the sentence

2019-01-20 19:52 UTC, Slashek commented
hmm, @diana-lakatos ^

2019-01-21 09:16 UTC, diana-lakatos commented
I discussed this with Adam, and we're going with `platformOS` even if it's in the beginning of the sentence to keep the branding consistent.

2019-01-21 09:20 UTC, pavelloz commented
Good stuff :)

2019-01-21 09:20 UTC, pavelloz approved these changes

2019-01-21 09:20 UTC, merged