Rename custom model type to model schema
Platform-OS/platformos-documentation pull request #588
Opened 2019-06-21 10:22 UTC by ignacy

Rename Custom Model Type to Model Schema

Part of https://github.com/mdyd-dev/desksnearme/issues/8384 **Please don't merge until backend gets deployed.**

2019-06-21 10:33 UTC, pavelloz commented on marketplace_builder/views/pages/tutorials/custom-model-types/custom-model-types.liquid
> +Model Schema definitions are placed in the `model_schemas` directory.
```suggestion
Model Schemas are placed in the `model_schemas` directory.
```

2019-06-21 10:35 UTC, pavelloz commented on marketplace_builder/views/pages/tutorials/custom-model-types/persisting-data-with-customizations.liquid
> +  * **custom model type definition delete** - you can only delete your Model Schema object if there is no related Customization object. Use [customizations_delete_all](/api-reference/graphql/g/mut/cu
```suggestion
  * **model schema delete** - you can only delete your Model Schema object if there is no related Customization object. Use [customizations_delete_all](/api-reference/graphql/g/mut/customizations_delete_all) mutation to delete all related Customization objects.
```

2019-06-21 10:38 UTC, pavelloz requested changes

2019-06-21 10:38 UTC, pavelloz commented on marketplace_builder/views/pages/tutorials/custom-model-types/persisting-data-with-customizations.liquid
>    * **name change** - as platformOS detects CustomModelType definition by its name, if you change it is equal with adding new CustomModelType, please note that Customization objects are not automatic
```suggestion
  * **name change** - as platformOS detects ModelSchema definition by its name, if you change it is equal with adding new ModelSchema, please note that Customization objects are not automatically migrated and will be treated as orphaned with next deploy attempt, see error message above.
```

Dont know about that one.

2019-06-21 10:38 UTC, pavelloz commented on marketplace_builder/views/partials/shared/nav/tutorials.liquid
> +    <li><a href="/tutorials/custom-model-types/custom-model-types">Model Schemas /a></li>
```suggestion
    <li><a href="/tutorials/custom-model-types/custom-model-types">Model Schemas</a></li>
```

2019-06-28 11:45 UTC, Slashek commented on marketplace_builder/views/partials/shared/nav/tutorials.liquid
> +    href="/tutorials/custom-model-types/custom-model-types">Model Schemas</a>
should we change `custom-model-types` to `model-schemas` in the url as well?

2019-06-28 11:49 UTC, Slashek commented
updated the links cc @pavelloz

2019-06-28 11:52 UTC, pavelloz approved these changes

2019-07-01 18:08 UTC, merged

2019-07-01 21:50 UTC, pavelloz commented
```+ marketplace-kit deploy

Falling back to legacy app-directory name. Please consinder renaming marketplace_builder to app

[18:11:33] Archive size: 1.02 MB

- Deploying to: https://documentation.platformos.com/


[Deploy] Validation failed: Query string InputObject 'CustomizationInputType' doesn't accept argument 'model_schema_name' 

 {

  "file_path": "graph_queries/mutations/update_page_contributors.graphql"

}


[18:11:35] undefined

```